spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments-api
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: user
      password: password
      roles: USER

springdoc:
  paths-to-match: /transactions/**, /users/**, /auth/**
  paths-to-exclude: /users/
  swagger-ui:
    path: /documentation
    title: API de transações entre usuários lojistas e comuns

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}



