spring:
  datasource:
    url: jdbc:h2:mem:transations
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

springdoc:
  paths-to-match: /transactions/**, /users/**
  paths-to-exclude: /users/
  swagger-ui:
    path: /documentation
    title: API de transações entre usuários lojistas e comuns
